### ISSUE TITLE
High-DPI environment doesn't apply to window size and coordinates

### ISSUE THREAD

**Issue by jernejs** [nefarius/vicius#41]
I just got a notification "Updates for HidHide are available". There are two problems with this window:
1. the window is tiny (looks like it's rendered at 96 DPI without scaling; my screens are set to 216 DPI)
2. the window does not respond to clicks anywhere, though I can drag it around

![image](https://github.com/nefarius/HidHide/assets/1800143/2e5b2f64-4e97-4711-befb-37d5dbde4772)

According to Programs and Features I have HidHide 1.5.212 installed at the moment.

### Steps to reproduce

Just wait for the updater window to appear

**Comment by nefarius** [comment]
OK I did some digging and it appears that SFML needs to be configured properly to support DPI awareness and the developer has to react accordingly to scale everything. Interesting. @jernejs can you share your settings so I can replicate them, Screenshots or whatever shows how your monitor is set up.

**Comment by jernejs** [comment]
I've got two 27″ 5120x2880 monitors, both are set to 225% DPI in Windows; not sure if it matters, but I also use High Contrast mode. Here's a screenshot of my Display Settings:
![image](https://github.com/nefarius/vicius/assets/1800143/71ed14e5-d227-4644-a444-a149b74c454e)

Also, I need to amend my report – after I sent the bug report, the updater started responding to clicks, though I have no idea why (I tried clicking everything first, including the Cancel button, but the only response was dragging the window when I did that near the top; dragging also wasn't working quite properly – it'd lose tracking fairly quickly; after I moved the window to the left side of my monitor, I noticed that "Display update details now" started responding to mouse hovering, after which I was able to click it and proceed with the update).

**Comment by nefarius** [comment]
Partially good news then. Still the DPI topic is on my TODO anyway.

**Comment by nefarius** [comment]
Some research resources:

- [DPI-aware IMGUI](https://ruby0x1.github.io/machinery_blog_archive/post/dpi-aware-imgui/index.html)
- [DPI awareness on Windows](https://en.sfml-dev.org/forums/index.php?topic=28770.msg178734#msg178734)
- [DPI-Scaling on Windows](https://en.sfml-dev.org/forums/index.php?topic=29282.msg180688#msg180688)

**Comment by nefarius** [comment]
Also opened [an issue about this](https://github.com/SFML/imgui-sfml/issues/284) over at `imgui-sfml`, fingers crossed 🤞

**Comment by nefarius** [comment]
Small progress but oh dear, what have I unleashed 🤯 

![image](https://github.com/nefarius/vicius/assets/286631/25adfbb9-a4aa-4d80-a5d6-63cdfb42df10)

**Comment by nefarius** [comment]
Another [example implementation](https://github.com/ocornut/imgui/discussions/3925) to look at 😃

**Comment by nefarius** [comment]
Progress! 🥳 

Tested at 150%:

![image](https://github.com/nefarius/vicius/assets/286631/0a246ed3-b105-441e-8a6e-79ee0a1f0fbb)

![image](https://github.com/nefarius/vicius/assets/286631/c4e1e29c-8e60-4654-a4ba-3b386c58d660)

![image](https://github.com/nefarius/vicius/assets/286631/1e64e4a1-55db-480e-8473-d7ee9062b9c0)

@jernejs once I have a test build would you be available to help testing with your system and give feedback about the look and feel?

**Comment by jernejs** [comment]
> @jernejs once I have a test build would you be available to help testing with your system and give feedback about the look and feel?

Sure.

**Comment by nefarius** [comment]
> > @jernejs once I have a test build would you be available to help testing with your system and give feedback about the look and feel?
> 
> Sure.

Neat! So in case you already updated HidHide to the latest version, first run this in an elevated PowerShell/Terminal:

```PowerShell
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Nefarius Software Solutions e.U.\HidHide' -Name Version -Value "1.4.0" -Force
```

Next [download and run this build](http://sharex.nefarius.at/u/nefarius_HidHide_Updater.exe) and share screenshots and your opinion on how it scales, and maybe even a video clip of navigating through the pages.

Cheers

**Comment by jernejs** [comment]
Looks fine now:
![image](https://github.com/nefarius/vicius/assets/1800143/a16537b5-35df-4e28-b88d-63aead9d67cc)
![image](https://github.com/nefarius/vicius/assets/1800143/899e9dab-05c7-4ec7-beae-31fa3dcf7745)
![image](https://github.com/nefarius/vicius/assets/1800143/776edaf2-0db1-45d4-ae6d-cb51918073fa)

Also no problems with clicking the buttons, though trying to move the window still loses tracking sometimes.

**Comment by nefarius** [comment]
Very cool, thanks for testing! I will see if I can improve the dragging situation further.

**Comment by nefarius** [comment]
Related to #54

@jernejs I also fixed (at least on my end) the focus problem (buttons not clickable on first window launch), could you help me test [nefarius_HidHide_Updater.zip](https://github.com/user-attachments/files/16314484/nefarius_HidHide_Updater.zip) please, thx.

**Comment by jernejs** [comment]
I've got a bit of a problem – after installing the previous test version, HidHide Updater kept popping up every time I started Windows (and it did this even if I let it update), so I finally had enough and uninstalled HidHide yesterday; now when I try running the new updater, I get:
![image](https://github.com/user-attachments/assets/d0bcd175-ff1e-4e1e-80b4-fe5632e0f9f5)

Somewhat related, I've always had problems updating HidHide – it always requires a restart, and unless I let it restart immediately, it never managed to update.

**Comment by nefarius** [comment]
Yeah that message is expected; the product to check is not present on the system.

To have HidHide update successfully you **must let it reboot** whenever it asks you to. This will eventually be fixed in the future, there are open issues about it, but I do not have the time to tackle this right now.

Back to topic; if you just install an older version of HidHide normally and then invoke the exe I uploaded, it should immediately work navigating in it.
