### ISSUE TITLE
HidHide updater gives CURLE_OPERATION_TIMEOUT

### ISSUE THREAD

**Issue by dixtuel** [nefarius/vicius#47]
### Bug description

HidHide updater gives CURLE_OPERATION_TIMEOUT error when I try to update.

### Screenshots

![Ekran görüntüsü 2024-06-29 205047](https://github.com/nefarius/HidHide/assets/121726849/df503194-28b3-4bc5-b238-81385ff1662a)

- [] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

**Comment by nefarius** [comment]
Time to make it more robust against unstable networks 👀 

![image](https://github.com/nefarius/vicius/assets/286631/f492822c-c4c5-4884-ab3b-89af76070537)

**Comment by nefarius** [comment]
For archival purposes; I accidentally left in the timeout of 5 seconds, that might have been too optimistic for the vast majority of network qualities existing out there. Also adding some retry logic and whatever else I can do to get the stuff downloaded successfully 💪
